### ISSUE TITLE
Weird things with this updated starter kit

### ISSUE THREAD

**Issue by partyparrotgreg** [datocms/nextjs-starter-kit#1]
My records are typed as `unknown` and I can't map through them but it's an obvious collection of items.
<img width="583" alt="image" src="https://github.com/user-attachments/assets/8128ef6a-4d89-4a53-8d06-9b7021df46cb">

Also, an example like a blog would be much better rather than this. Previous starter kits were much better

Another thing is that I don't understand the API tokens used here as the Settings don't reflect the configuration used in the starter kit.

**Comment by stefanoverna** [comment]
> My records are typed as unknown and I can't map through them but it's an obvious collection of items.

When the DatoCMS schema (models/fields) gets updated, you should locally run:

```
npm run generate-schema
```

so that gql.tada gets the updated GraphQL schema! I'll add that to the README, thanks.

---

> Another thing is that I don't understand the API tokens used here as the Settings don't reflect the configuration used in the starter kit.

Not sure what you mean.. :/ Can you elaborate a bit?

--- 

> Also, an example like a blog would be much better rather than this. Previous starter kits were much better

Everyone has their own opinions on this... we decided to create extremely basic starters that just show how to hook DatoCMS into the framework, without being opinionated about what type of site one wants to create. Offering a starter like a blog is too specific, and it can't be used by those who want to start with new custom projects.

If you want complete examples, you should take a look at our full-fledged demos: https://www.datocms.com/marketplace/starters
